---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-miner01
  namespace: default
spec:
  storageClassName: "nfs-client-for-observability"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-miner02
  namespace: default
spec:
  storageClassName: "nfs-client-for-observability"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-miner03
  namespace: default
spec:
  storageClassName: "nfs-client-for-observability"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-bootnode
  namespace: default
spec:
  storageClassName: "nfs-client-for-observability"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    name: volume-ethmonitor
  name: volume-ethmonitor
spec:
  storageClassName: "nfs-client-for-observability"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: volume-mongodb
  name: volume-mongodb
spec:
  storageClassName: "nfs-client-for-observability"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
---
